#+TITLE: UnicoJS Documentation
#+SETUPFILE: "../templates/setup.org"


* Unico, a reactive framework
  Unico is a js framework built on top of Facebook React and inspired
  by Angular. It is suitable for small widget as well as full single
  page applications.

* Installation
  Download Unico from the release page on github: https://github.com/harlock/unicojs/releases
  You can choose one of these versions:
  * unico.core.js: Just the framework. You must download and require dependencies.
  * unico.js: Bundle with unico and its dependencies. Development version.
  * unico.min.js: Production ready build.
* Controllers
#+begin_html
<iframe width="100%" height="300" src="http://jsfiddle.net/txotin/czbjsvr2/embedded/html,js,result" allowfullscreen="allowfullscreen" frameborder="0"></iframe>
#+end_html

    In order to use Unico as an standalone framework in your
    application, you should add the tag 'controller' to the
    container. Controllers are responsible of provide data to the view
    and execute callbacks on user actions.
* Directives
  Directives are the bridge between react elements and your
  code. Directives give you the chance to manipulate the DOM node,
  add custom listeners, or change the element behavior

** Built in directives
*** if and unless
    These directives control the visibility of the element.

    #+begin_html
    <iframe width="100%" height="300" src="http://jsfiddle.net/txotin/z3qvh5wh/embedded/html,js,result" allowfullscreen="allowfullscreen" frameborder="0"></iframe>
    #+end_html

*** repeat
    This directive let you iterate over arrays and objects.

    #+begin_html
    <iframe width="100%" height="300" src="http://jsfiddle.net/txotin/8zhhomrL/embedded/html,js,result" allowfullscreen="allowfullscreen" frameborder="0"></iframe>
    #+end_html

*** click
    This directive execute a callback on click events. After execute the callback, it check for changes and update the view.

    #+begin_html
    <iframe width="100%" height="300" src="http://jsfiddle.net/txotin/z3qvh5wh/embedded/html,js,result" allowfullscreen="allowfullscreen" frameborder="0"></iframe>
    #+end_html

*** model
    This directive provide 2 way data binding.

    #+begin_html
    <iframe width="100%" height="500" src="http://jsfiddle.net/txotin/z9w9ms5t/embedded/html,js,result" allowfullscreen="allowfullscreen" frameborder="0"></iframe>
    #+end_html

*** submit
    This directive let you interact with forms

    #+begin_html
    <iframe width="100%" height="300" src="http://jsfiddle.net/txotin/nwto8xL8/embedded/html,js,result" allowfullscreen="allowfullscreen" frameborder="0"></iframe>
    #+end_html
** TODO [#C] Create custom directives

* TODO Components
Components let you build reusable web components with its own controller.
* Using React classes as Unico components
If you want to integrate native react classes you can define a new
component and set the propety reactClass of meta. The framework
will call the react class with two properties, ctx and meta.
#+begin_html
  <iframe width="100%" height="500" src="http://jsfiddle.net/txotin/pwcdz9h0/embedded/js,html,result" allowfullscreen="allowfullscreen" frameborder="0"></iframe>
#+end_html
* TODO Models
* TODO Router and Single Page Applications
